### ISSUE TITLE
Not specified dependencies

### ISSUE THREAD

**Issue by gamoutatsumi** [nine7nine/pkgbuild-easystroke#1]
I thanks to this repository and you! 
I tryed install easystroke, but in AUR to went wrong.

By the way, this package seems want `vala` package, but not specified in `PKGBUILD`.

I was helped by this repository, but I wasted 5 minuetes.

**Comment by nine7nine** [comment]
Ah, sorry about that. Vala is definitely a dependency.

I will add it a bit later. I have a bugfix / commit i need to add to the source code repo as well.

I'll try and get that up tonight,but if not; tomorrow.

Thanks.

**Comment by nine7nine** [comment]
Added Vala to makedepends()

[53001f3](https://github.com/nine7nine/pkgbuild-easystroke/commit/53001f3c6d4240b7de66ebb5e5ab701d3b4bfcff)
